title: pizza
url: https://www.matttech.dev/
baseurl: 

author: Disha Patel
description: Discovering the world with my vision.

include: ['_pages']

collections_dir: series

collections:
  home:
    output: true
  supreme:
    output: true
  photo:
    output: true
    
markdown: kramdown
kramdown:
  input: GFM
